import { pgTable, serial, varchar, decimal, timestamp } from 'drizzle-orm/pg-core';

export const ucSections = pgTable('uc_sections', {
  id: serial('id').primaryKey(),
  section: varchar('section', { length: 50 }).notNull(),
  height_mm: decimal('height_mm', { precision: 10, scale: 2 }).notNull(),
  width_mm: decimal('width_mm', { precision: 10, scale: 2 }).notNull(),
  web_thickness_mm: decimal('web_thickness_mm', { precision: 10, scale: 2 }).notNull(),
  flange_thickness_mm: decimal('flange_thickness_mm', { precision: 10, scale: 2 }).notNull(),
  internal_height_mm: decimal('internal_height_mm', { precision: 10, scale: 2 }).notNull(),
  root_radius_mm: decimal('root_radius_mm', { precision: 10, scale: 2 }).notNull(),
  depth_mm: decimal('depth_mm', { precision: 10, scale: 2 }).notNull(),
  cross_sectional_area_cm2: decimal('cross_sectional_area_cm2', { precision: 10, scale: 2 }).notNull(),
  second_moment_y_cm4: decimal('second_moment_y_cm4', { precision: 10, scale: 2 }).notNull(),
  second_moment_z_cm4: decimal('second_moment_z_cm4', { precision: 10, scale: 2 }).notNull(),
  polar_moment_cm4: decimal('polar_moment_cm4', { precision: 10, scale: 2 }).notNull(),
  radius_gyration_y_mm: decimal('radius_gyration_y_mm', { precision: 10, scale: 2 }).notNull(),
  radius_gyration_z_mm: decimal('radius_gyration_z_mm', { precision: 10, scale: 2 }).notNull(),
  polar_radius_gyration_mm: decimal('polar_radius_gyration_mm', { precision: 10, scale: 2 }).notNull(),
  max_elastic_modulus_y_cm3: decimal('max_elastic_modulus_y_cm3', { precision: 10, scale: 2 }).notNull(),
  max_elastic_modulus_z_cm3: decimal('max_elastic_modulus_z_cm3', { precision: 10, scale: 2 }).notNull(),
  elastic_modulus_y_cm3: decimal('elastic_modulus_y_cm3', { precision: 10, scale: 2 }).notNull(),
  elastic_modulus_z_cm3: decimal('elastic_modulus_z_cm3', { precision: 10, scale: 2 }).notNull(),
  shear_area_y_cm2: decimal('shear_area_y_cm2', { precision: 10, scale: 2 }).notNull(),
  shear_area_z_cm2: decimal('shear_area_z_cm2', { precision: 10, scale: 2 }).notNull(),
  torsional_constant_cm4: decimal('torsional_constant_cm4', { precision: 10, scale: 2 }).notNull(),
  torsional_constant_st_venant_cm4: decimal('torsional_constant_st_venant_cm4', { precision: 10, scale: 2 }).notNull(),
  torsional_modulus_cm3: decimal('torsional_modulus_cm3', { precision: 10, scale: 2 }).notNull(),
  max_warping_function_cm2: decimal('max_warping_function_cm2', { precision: 10, scale: 2 }).notNull(),
  warping_constant_cm6: decimal('warping_constant_cm6', { precision: 10, scale: 2 }).notNull(),
  warping_radius_gyration_mm: decimal('warping_radius_gyration_mm', { precision: 10, scale: 2 }).notNull(),
  warping_modulus_cm4: decimal('warping_modulus_cm4', { precision: 10, scale: 2 }).notNull(),
  plastic_modulus_y_cm3: decimal('plastic_modulus_y_cm3', { precision: 10, scale: 2 }).notNull(),
  plastic_modulus_z_cm3: decimal('plastic_modulus_z_cm3', { precision: 10, scale: 2 }).notNull(),
  plastic_warping_modulus_cm4: decimal('plastic_warping_modulus_cm4', { precision: 10, scale: 2 }).notNull(),
  plastic_modulus_webs_y_cm3: decimal('plastic_modulus_webs_y_cm3', { precision: 10, scale: 2 }).notNull(),
  plastic_modulus_flanges_z_cm3: decimal('plastic_modulus_flanges_z_cm3', { precision: 10, scale: 2 }).notNull(),
  plastic_shape_factor_y: decimal('plastic_shape_factor_y', { precision: 10, scale: 3 }).notNull(),
  plastic_shape_factor_z: decimal('plastic_shape_factor_z', { precision: 10, scale: 3 }).notNull(),
  plastic_warping_shape_factor: decimal('plastic_warping_shape_factor', { precision: 10, scale: 3 }).notNull(),
  plastic_area_y_cm2: decimal('plastic_area_y_cm2', { precision: 10, scale: 2 }).notNull(),
  plastic_area_z_cm2: decimal('plastic_area_z_cm2', { precision: 10, scale: 2 }).notNull(),
  plastic_axial_force_kn: decimal('plastic_axial_force_kn', { precision: 10, scale: 2 }).notNull(),
  plastic_shear_force_y_kn: decimal('plastic_shear_force_y_kn', { precision: 10, scale: 2 }).notNull(),
  plastic_shear_force_z_kn: decimal('plastic_shear_force_z_kn', { precision: 10, scale: 2 }).notNull(),
  plastic_moment_y_knm: decimal('plastic_moment_y_knm', { precision: 10, scale: 2 }).notNull(),
  plastic_moment_z_knm: decimal('plastic_moment_z_knm', { precision: 10, scale: 2 }).notNull(),
  ultimate_axial_force_kn: decimal('ultimate_axial_force_kn', { precision: 10, scale: 2 }).notNull(),
  mass_per_unit_length_kgm: decimal('mass_per_unit_length_kgm', { precision: 10, scale: 2 }).notNull(),
  surface_area_per_unit_length_m2m: decimal('surface_area_per_unit_length_m2m', { precision: 10, scale: 2 }).notNull(),
  volume_per_unit_length_cm3m: decimal('volume_per_unit_length_cm3m', { precision: 10, scale: 2 }).notNull(),
  surface_area_to_volume_ratio_1m: decimal('surface_area_to_volume_ratio_1m', { precision: 10, scale: 3 }).notNull(),
  web_area_cm2: decimal('web_area_cm2', { precision: 10, scale: 2 }).notNull(),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull()
}); 